### ISSUE TITLE
Modificar OptionPerVote en BD

### ISSUE THREAD

**Issue by ArturoRonda** [Proyecto-EGC-G1/CabinaSlack-EGC-G1#6]
Desde recuento de votos necesitamos implementar un nuevo campo integer dentro de la clase OptionPerVote.

El nuevo campo permite hacer un recuento teniendo en cuenta el orden de las posibles respuestas, podría ser 0 no null,  el valor vendría dado por la preferencia que de el votante a cada respuesta.

Desde integración nos han solicitado vuestra confirmación.

**Comment by edubsteep** [comment]
Damos la confirmación tras la comunicación con el grupo.
