### ISSUE TITLE
Mejora visualización comandos

### ISSUE THREAD

**Issue by edubsteep** [Proyecto-EGC-G1/CabinaSlack-EGC-G1#61]
Mejora de visualizacion de todos los comandos, así como, el acceso a ellos

**Comment by edubsteep** [comment]
Terminado la mejora gráfica de las preguntas de la aplicación

**Comment by alex395** [comment]
Se ha mejorado el modo de interacción con el bot, añadiendo una funcionalidad para poder citarlo.
