### ISSUE TITLE
Pulir funcionalidad de cambio en la defensa

### ISSUE THREAD

**Issue by budia95** [Proyecto-EGC-G1/CabinaSlack-EGC-G1#67]
La funcionalidad será la de que cada vez que se mencione al bot este lo detectará y te aconsejará que utilices tal comando. Ahora, habrá que buscar la forma de que detecte la mención y no solo su nombre o la palabra "bot"

**Comment by edubsteep** [comment]
Realizado pruebas para la defensa.
