### ISSUE TITLE
Crear una nueva funcionalidad para que el bot detecte cuando están hablando de él. 

### ISSUE THREAD

**Issue by alex395** [Proyecto-EGC-G1/CabinaSlack-EGC-G1#69]
Sería una nueva funcionalidad en la que nuestro bot detecte cuando alguien escribe la palabra "bot" y conteste aportando ayuda sobre los comandos indicandote
el comando help.

**Comment by budia95** [comment]
Se ha terminado de realizar la funcionalidad en la que reconoce la ID y este responderia con un chat.message
